# Generated by Django 2.2.14 on 2020-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='tests',
        ),
        migrations.AddField(
            model_name='homepage',
            name='line',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
